# Generated by Django 3.2.3 on 2023-10-06 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231006_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
